fix up bss-multicast demo, convert to "dotest"

diff --git a/demos/bss-multicast/dotest b/demos/bss-multicast/dotest
--- a/demos/bss-multicast/dotest
+++ b/demos/bss-multicast/dotest
@@ -1,43 +1,36 @@
 #!/bin/bash
-#
+
 # Scott Burleigh
 # September 11, 2012
-#
-# documentation boilerplate
+
+set -e  # Exit immediately if a command exits with a non-zero status.
+trap 'echo "An error occurred. Exiting."; exit 1;' ERR
+
+# Documentation boilerplate
 CONFIGFILES=" \
 ./global.ionrc \
 ./1.ipn.bss/node.ionconfig \
 ./1.ipn.bss/node.ionrc \
 ./1.ipn.bss/node.ionsecrc \
-./1.ipn.bss/node.bssprc \
 ./1.ipn.bss/node.bprc.1 \
-./1.ipn.bss/node.ipnrc \
-./1.ipn.bss/node.imcrc \
-./1.ipn.bss/node.bprc.2 \
+./1.ipn.bss/node.ltprc \
 ./1.ipn.bss/node.owltsim \
 ./2.ipn.bss/node.ionconfig \
 ./2.ipn.bss/node.ionrc \
 ./2.ipn.bss/node.ionsecrc \
-./2.ipn.bss/node.bssprc \
 ./2.ipn.bss/node.bprc.1 \
-./2.ipn.bss/node.ipnrc \
-./2.ipn.bss/node.imcrc \
-./2.ipn.bss/node.bprc.2 \
+./2.ipn.bss/node.ltprc \
 ./3.ipn.bss/node.ionconfig \
 ./3.ipn.bss/node.ionrc \
 ./3.ipn.bss/node.ionsecrc \
-./3.ipn.bss/node.bssprc \
 ./3.ipn.bss/node.bprc.1 \
-./3.ipn.bss/node.ipnrc \
-./3.ipn.bss/node.imcrc \
+./3.ipn.bss/node.ltprc \
 ./3.ipn.bss/node.bprc.2 \
 ./4.ipn.bss/node.ionconfig \
 ./4.ipn.bss/node.ionrc \
 ./4.ipn.bss/node.ionsecrc \
-./4.ipn.bss/node.bssprc \
 ./4.ipn.bss/node.bprc.1 \
-./4.ipn.bss/node.ipnrc \
-./4.ipn.bss/node.imcrc \
+./4.ipn.bss/node.ltprc \
 ./4.ipn.bss/node.bprc.2 \
 "
 
@@ -48,20 +41,10 @@ echo
 echo "PURPOSE: Demonstrate the functionality of Bundle Streaming Service.
 Demonstrates BSS multicast:
 
-REVISE
 This demo simulates the multicast streaming by sending a stream 
-of bundles from node 1 to multicast group 19 for 30 seconds. The network
-comprises four nodes in a diamond topology (1 is in continuous LTP contact
-with 2 and 3, both of which are in continuous LTP contact with node 4; in
-addition, nodes 2 and 3 are in continuous LTP contact). Nodes 1, 3, and 4 (but
-not 2) are members of multicast group 19.
-
-The communication channel between node 1 and node 2 presents packet losses
-(on the order of 10%); BSSP retransmission enables these losses to be recovered.
-At the receiver's end, only the frames that arrive in-order get immediately
-displayed while the out-of-order frames are stored in database for later
-processing. After 30 seconds the stream can be replayed in its entirety by
-using the playback-mode functionality of the BSS receiving application."
+of bundles from node 1 to multicast group 19 for 30 seconds. The network 
+is a tree with the following edges all running LTP: (1,2), (2,3) and (2,4).
+Node 3 and 4 are part of multicast group 19."
 
 echo
 echo "CONFIG: 4 node custom BSS:"
@@ -82,29 +65,42 @@ echo "Starting ION..."
 export ION_NODE_LIST_DIR=$PWD
 rm -f ./ion_nodes
 sleep 1
-# Start nodes.
+
+# Start nodes
 cd 1.ipn.bss
 echo "Starting node 1..."
 ./ionstart >& node1.stdout &
 sleep 5
+
 cd ../2.ipn.bss
 echo "Starting node 2..."
 ./ionstart >& node2.stdout &
 sleep 1
+
 cd ../3.ipn.bss
 echo "Starting node 3..."
 ./ionstart >& node3.stdout &
 sleep 1
+
 cd ../4.ipn.bss
 echo "Starting node 4..."
 ./ionstart >& node4.stdout &
 
-# Wait for all nodes to be configured.
-sleep 25
+# Wait for all nodes to be configured
+sleep 5
 
-exit 0
+# Register node 3 and 4 in imc:19.0
+cd ../3.ipn.bss
+echo "Register node 3 into multicast group imc:19.0"
+bpadmin node.bprc.2
 
-# Start BSS receiver on nodes 3 and 4.
+cd ../4.ipn.bss
+echo "Register node 4 into multicast group imc:19.0"
+bpadmin node.bprc.2
+
+sleep 5
+
+# Start BSS receiver on nodes 3 and 4
 echo
 echo "Starting bssrecv application..."
 cd ../3.ipn.bss
@@ -123,7 +119,7 @@ pkill -SIGINT bssStreamingApp
 TOTIME=$(date +"%Y/%m/%d-%T")
 echo
 
-# Give nodes enough time to receive all the reforwarded frames from node 1.
+# Give nodes enough time to receive all the reforwarded frames from node 1
 echo "Wait 15 seconds to ensure the complete reception of the stream from node 2..."
 sleep 15
 pkill bssrecv
@@ -138,7 +134,7 @@ echo
 sleep 70
 pkill bssrecv
 
-# Shut down ION processes.
+# Shut down ION processes
 echo
 echo "Stopping ION..."
 cd ../1.ipn.bss
@@ -150,8 +146,8 @@ cd ../3.ipn.bss
 cd ../4.ipn.bss
 ./ionstop &
 
-# Give all nodes time to shut down, then clean up.
+# Give all nodes time to shut down, then clean up
 sleep 15
 killm
-echo "BSS demo completed."
-exit $RETVAL
+echo "BSS multicast demo completed."
+echo "Please monitor real-time display for node 3 and 4 to verify demonstration was actually successful."
