Make attempting to run ipn and bss at the same time an error

diff --git a/ionscript b/ionscript
--- a/ionscript
+++ b/ionscript
@@ -208,6 +208,11 @@ while getopts ":i:d:c:p:b:l:I:O:t:s:a:m:B:hA" options; do
 	esac
 done
 
+if [[ ! -z "${BSSRC}" ]] && [[ ! -z "${IPNRC}" ]] ; then
+	echo "Error: bss and ipn are mutually exclusive!"
+	exit 1
+fi
+
 # if there is an input file, we will convert INPUTFILE -> ionrc, dtn2rc, ipnrc, etc
 if [[ -n "${INPUTFILE}" ]] ; then
 	echo
diff --git a/ionstart b/ionstart
--- a/ionstart
+++ b/ionstart
@@ -175,6 +175,11 @@ if [[ "${failure}" == "TRUE" ]] ; then
 	exit 1
 fi
 
+if [[ ! -z "${BSSRC}" ]] && [[ ! -z "${IPNRC}" ]] ; then
+	echo "Error: bss and ipn are mutually exclusive!"
+	exit 1
+fi
+
 if [[ ! -z "${CONFIGFILE}" ]] ; then
 	echo
 	echo "Now running startup script using ${CONFIGFILE}"
