update with missing processes, POSIX compliant comparisons, and best practice command substitution quoting - additional update possible

diff --git a/killm b/killm
--- a/killm
+++ b/killm
@@ -13,7 +13,7 @@ OS_VERS=""
 # truncated username so we trim the username to 10 characters.
 # NOTE: This may cause conflicts with long usernames with similar beginning
 #       characters. We'll look for a more robust solution in the near future.
-USERNAME_CUT=`echo $USER | cut -c 1-10`
+USERNAME_CUT=$(echo "$USER" | cut -c 1-10)
 KILLPROCESSLIST="acsadmin lt-acsadmin \
 	acslist lt-acslist \
 	amsbenchr lt-amsbenchr \
@@ -22,6 +22,7 @@ KILLPROCESSLIST="acsadmin lt-acsadmin \
 	amshello lt-amshello \
 	amslog lt-amslog \
 	amslogprt lt-amslogprt \
+	amsmib lt-amsmib \
 	amsshell lt-amsshell \
 	amsstop lt-amsstop \
 	aoslsi lt-aoslsi \
@@ -144,6 +145,7 @@ KILLPROCESSLIST="acsadmin lt-acsadmin \
 	tcpbso lt-tcpbso \
 	tcpcli lt-tcpcli \
 	tcpclo lt-tcpclo \
+	tcputa lt-tcputa \
 	udp2file lt-udp2file \
 	udpbsi lt-udpbsi \
 	udpbso lt-udpbso \
@@ -156,12 +158,12 @@ KILLPROCESSLIST="acsadmin lt-acsadmin \
 sw_vers 2> /dev/null > /dev/null
 
 #if sw_vers ran, then we're on a mac system
-if [[ $? -eq 0 ]]; then  
-	OS_VERS=`sw_vers | grep 10.4`
+if [ "$?" -eq 0 ]; then  
+	OS_VERS=$(sw_vers | grep 10.4)
 fi
 
 OSNAME=`uname`
-if [ "$OSNAME" == "SunOS" ]; then
+if [ "$OSNAME" = "SunOS" ]; then
     KILLCMD="pkill"
 	PS="/usr/bin/ps"
 	PS_ARGS="-fe"
@@ -170,7 +172,7 @@ else
     KILLCMD="killall"
 	PS="ps"
 	PS_ARGS="-fe"
-	if [[ "$(uname -m)" == "x86_64" ]]; then
+	if [ "$(uname -m)" = "x86_64" ]; then
 		PROCESS_LIMIT=64
 	else
     	PROCESS_LIMIT=32
@@ -196,8 +198,8 @@ PSFILE="/tmp/ps.$$"
 ${PS} ${PS_ARGS} > ${PSFILE}
 # see if any of those still-running processes belong to ION
 for PROC in ${KILLPROCESSLIST}; do
-	grep "[^-a-zA-Z]${PROC}$" ${PSFILE} | grep -v "defunct" | \
-		awk '{printf("  *** Unknown error: process %s not killed...try rebooting\n", $NF);}'
+    grep "[^-a-zA-Z]${PROC}$" "${PSFILE}" | grep -v "defunct" | \
+        awk '{printf("  *** Unknown error: process %s not killed...try rebooting\n", $NF);}'
 done
 
 rm -f ${PSFILE}
