update to prevent any tx attempt if address is invalid

diff --git a/tests/ipaddr-caching-udpclo/dotest b/tests/ipaddr-caching-udpclo/dotest
--- a/tests/ipaddr-caching-udpclo/dotest
+++ b/tests/ipaddr-caching-udpclo/dotest
@@ -116,8 +116,9 @@ HOSTS_FILE="/etc/hosts"
 BACKUP_FILE="/tmp/hosts.bak"
 ENTRY="127.0.1.3    test3.local"
 LOG_FILE="ion.log"
-SEARCH_STRING1="udpclo: Abandoning bundle due to invalid address"
-SEARCH_STRING2="udpclo: Successfully resolved hostname: test3.local"
+SEARCH_STRING1="Initial hostname resolution failed. (test3.local)"
+SEARCH_STRING2="can't get address for host"
+SEARCH_STRING3="udpclo: Successfully resolved hostname: test3.local"
 LINE_NUM=1
 
 # Check for sudo availability
@@ -151,38 +152,59 @@ echo "Starting bpsink application..."
 echo ""
 cd ../3.bench.udp
 bpsink ipn:3.1 &
-BPCOUNTER_PID=$!
+BPSINK_PID=$!
 sleep 1
 
+#
 # Step 1: Destination hostname not in DNS database or hosts file
+#
 echo ""
 echo "Step 1: Destination host not in DNS database or hosts file."
 echo ""
 
-echo "Sending three messages..."
-echo ""
-
 cd ../2.bench.udp
-bpsource ipn:3.1 "Hello!"
-bpsource ipn:3.1 "Hello2!"
-bpsource ipn:3.1 "Hello3!"
-sleep 10
-
-# Check ion.log for DNS lookup report
+# Check ion.log for initialization DNS lookup error report
 LINE_NUM=$(search_log_after_line "$LOG_FILE" "$SEARCH_STRING1" "$LINE_NUM")
 return_code=$?
 if [ $return_code -eq 0 ]; then
-	echo "SUCCESS: ion.log reported DSN lookup failure at line $LINE_NUM"
+	echo "SUCCESS: ion.log reported initial DSN lookup failure at line $LINE_NUM"
 else
 	echo "FAIL: No match or error (return code: -1)"
 	RETVAL=1
 fi
 
-bpstats
+#
+# Step 2: Sending bundle with invalid address
+#
 
-# Step 2: Destination hostname added back to DNS or hosts file
+echo "Send 1 message..."
 echo ""
-echo "Step 2: Destination hostname added back to DNS or hosts file."
+
+bptrace ipn:2.1 ipn:3.1 dtn:none 300 0.1 "Hello!"
+sleep 1
+
+bpstats
+cat ion.log | grep xmt
+
+echo ""
+echo "bpstats should show 1 message transmitted. UDPCLO has no stewardship, dequeued bundle is considered transmitted."
+echo ""
+
+# Check ion.log invalid address error report
+LINE_NUM=$(search_log_after_line "$LOG_FILE" "$SEARCH_STRING2" "$LINE_NUM")
+return_code=$?
+if [ $return_code -eq 0 ]; then
+	echo "SUCCESS: ion.log reported invalid address at transmit time on line $LINE_NUM"
+else
+	echo "FAIL: No match or error (cat ion.log | grep xmtreturn code: -1)"
+	RETVAL=1
+fi
+
+#
+# Step 3: Destination hostname added back to DNS or hosts file
+#
+echo ""
+echo "Step 3: Destination hostname added back to DNS or hosts file."
 echo ""
 
 # Append test3.local to hosts file
@@ -197,14 +219,36 @@ else
     exit 1
 fi
 
-# Sending several messages
+# Sending 3 messages
 echo ""
-echo "Sending 3 more messages after DNS restoration, it should resolve immediately"
-bpsource ipn:3.1 "Hello2!"
-sleep 10
+echo "Sending 1 message after DNS restoration, this will fail because re-resolve is not yet taken place but show as transmitted also."
+bptrace ipn:2.1 ipn:3.1 dtn:none 300 0.1 "Hello2!"
+sleep 1
+bpstats
+cat ion.log | grep xmt
+
+echo ""
+echo "Now wait for 60 seconds for address cache to refresh..."
+echo ""
+sleep 60
+
+echo ""
+echo "Now send two bundles."
+echo ""
+bptrace ipn:2.1 ipn:3.1 dtn:none 300 0.1 "Hello3!"
+bptrace ipn:2.1 ipn:3.1 dtn:none 300 0.1 "Hello4!"
+sleep 1
+
+bpstats
+cat ion.log | grep xmt
+
+echo ""
+echo "Sender bpstats should show total of 4 transmitted messages."
+echo ""
+sleep 1
 
 # Check ion.log for DNS lookup report
-LINE_NUM=$(search_log_after_line "$LOG_FILE" "$SEARCH_STRING2" "$LINE_NUM")
+LINE_NUM=$(search_log_after_line "$LOG_FILE" "$SEARCH_STRING3" "$LINE_NUM")
 return_code=$?
 if [ $return_code -eq 0 ]; then
 	echo "SUCCESS: ion.log reported DNS lookup success at line $LINE_NUM"
@@ -213,7 +257,23 @@ else
 	RETVAL=1
 fi
 
+# Check log on the receiving side
+cd ../3.bench.udp
 bpstats
+cat ion.log | grep rcv
+echo ""
+echo "Receiver bpstats should show 2 recived bundles."
+echo ""
+
+LINE_NUM=$(search_log_after_line "$LOG_FILE" "rcv" "1")
+return_code=$?
+if [ $return_code -eq 0 ]; then
+	echo "SUCCESS: ion.log reported DNS lookup success at line $LINE_NUM"
+else
+	echo "FAIL: No match or error (return code: -1)"
+	RETVAL=1
+fi
+sleep 10
 
 if [ "$RETVAL" -eq 1 ]
 then
@@ -222,6 +282,6 @@ fi
 
 echo -e "\nStopping ION..."
 cd ..
-./cleanup
+#./cleanup
 
 exit $RETVAL
