updating to address intermittent failures

diff --git a/tests/issue-319-parseSocketSpec/ionstart b/tests/issue-319-parseSocketSpec/ionstart
--- a/tests/issue-319-parseSocketSpec/ionstart
+++ b/tests/issue-319-parseSocketSpec/ionstart
@@ -12,7 +12,7 @@ bpadmin		amroc.bprc
 
 ../../system_up -i "p 30" -l "p 30" -b "p 30"
 
-if [ $? -eq 3 ]
+if [ "$?" -eq 3 ]
 then
 	echo ""
 else
@@ -21,6 +21,8 @@ else
 fi
 
 amsd mib.amsrc @ amsdemo test "" &
+sleep 1
+
 echo "Waiting for AMS cell census (9 seconds left)..."
 sleep 3
 echo "Waiting for AMS cell census (6 seconds left)..."
@@ -28,4 +30,8 @@ sleep 3
 echo "Waiting for AMS cell census (3 seconds left)..."
 sleep 3
 cp init.petition.log petition.log
+
+# add a little time due to some intermittent test failures
+sleep 3
 ramsgate amsdemo test &
+sleep 3
