updated to be more useful for data collection testing, but still work for regression tests

diff --git a/demos/bench-ltp/dotest b/demos/bench-ltp/dotest
--- a/demos/bench-ltp/dotest
+++ b/demos/bench-ltp/dotest
@@ -3,6 +3,52 @@
 # Scott Burleigh
 # August 9, 2012
 #
+# Shawn Ostermann
+# Made it more flexible for testing
+# October 11, 2023
+#
+
+#
+# testing configuration
+# (to make the numbers more readable)
+KB="000"
+MB="${KB}000"
+GB="${MB}000"
+# how many total bytes to transfer for each test
+TOTALBYTES=1${MB}
+TOTALBYTES=100${MB}
+# MAX number of bundles for any test (too many causes non-ION losses)
+# This really only affects really small size bundles
+MAXBUNDLES=100000
+# how many total seconds to allow each individual test to run before giving up
+# 10 minutes is probably plenty
+MAXSECONDS=120
+# what bundle sizes do you want to test
+# (list multiple values to cycle through them each)
+BUNDLESIZES="100 250 500 1000 1400 2500 5${KB} 10${KB} 25${KB} 50${KB} 100${KB} 1${MB} 10${MB} 100${MB}"
+BUNDLESIZES="100 250 500 1000 1400 2500 5${KB} 10${KB} 25${KB} 50${KB} 100${KB} 1${MB} 5${MB} 10${MB} 50${MB} 100${MB}"
+BUNDLESIZES="10 100 1${KB} 10${KB} 100${KB} 1${MB} 10${MB}"
+BUNDLESIZES="10 50 100 250 500 1000 1400 2500 5${KB} 10${KB} 25${KB} 50${KB} 100${KB} 1${MB} 5${MB} 10${MB}"
+# what THROUGHPUT to list in the contact plans (in ___BYTES___ per second)
+# (list multiple values to cycle through them each)
+THROUGHPUTS="100${MB} 1${GB} 10${GB} 100${GB}"
+THROUGHPUTS="10${GB}"
+# how many iterations of the test to run?
+ITERATIONS="25"
+
+
+#================================================================
+# You shouldn't need to adjust anything below this point 
+#================================================================
+
+# identify the test for later analysis
+echo "Date: `date`"
+echo "Hostname: `hostname`"
+echo "UnameOS: `uname -s`"
+echo "UnameProcessor: `uname -p`"
+echo "UnameMachine: `uname -m`"
+echo "UnameRelease: `uname -r`"
+echo "UnameAll: `uname -a`"
 
 # documentation boilerplate
 CONFIGFILES=" \
@@ -21,6 +67,7 @@ CONFIGFILES=" \
 ./3.bench.ltp/bench.ipnrc \
 "
 
+TOPDIR=`pwd`
 echo "########################################"
 echo
 pwd | sed "s/\/.*\///" | xargs echo "NAME: "
@@ -33,16 +80,19 @@ echo "PURPOSE: produce simple throughput benchmark results, for direct
 	over loopback UDP/IP; the results are therefore unaffected by network
 	traffic, router performance, or network interface card performance."
 
-echo
-echo "CONFIG: 2 node custom:"
-echo
-for N in $CONFIGFILES
-do
-	echo "$N:"
-	cat $N
-	echo "# EOF"
+if [ -n "$DEBUG" ]; then
 	echo
-done
+	echo "CONFIG: 2 node custom:"
+	echo
+	for N in $CONFIGFILES
+	do
+		echo "$N:"
+		cat $N
+		echo "# EOF"
+		echo
+	done
+fi
+
 echo "OUTPUT: Terminal messages will relay results."
 echo
 echo "########################################"
@@ -57,414 +107,158 @@ if [ $? != 0 ]; then
 	exit 1
 fi
 
-echo "Starting ION..."
-export ION_NODE_LIST_DIR=$PWD
-rm -f ./ion_nodes
-RETVAL=0
+ITERNUM=0
+while [ "${ITERNUM}" -lt ${ITERATIONS} ]; do
+	let "++ITERNUM"
+	echo "#########################################################################"
+	echo "##   Starting Iteration ${ITERNUM}"
+	echo "#########################################################################"
+	echo
 
-# Start nodes.
-cd 2.bench.ltp
-./ionstart
-cd ../3.bench.ltp
-./ionstart
+for THROUGHPUT in ${THROUGHPUTS}; do
+	echo "#########################################################################"
+	echo "##   Creating Contact Plan for max throughput: ${THROUGHPUT}"
+	echo "#########################################################################"
+	echo
 
-sleep 3
-echo ""
-echo "Test 1: 100,000 bundles of 1000 bytes each."
-cd ../3.bench.ltp
-bpcounter ipn:3.1 100000 &
-BPCOUNTER_PID=$!
-sleep 1
+	export ION_NODE_LIST_DIR=$PWD
+	rm -f ./ion_nodes
+	RETVAL=0
 
-# if bpcounter didn't start, then something went wrong and we definitely haven't passsed!
-# some ps don't like -p syntax, most do.
-if [ $1 == "windows" ]
-then
-		ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
-else
-		ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
-fi
-if [ $RETURN_VALUE -eq 0 ]
-then
-	echo "bpcounter couldn't be started."
-	echo "...benchmarking terminated."
-	exit 1
-fi
+	# Adjust the contact plan
+	cat > ./global.ionrc << EOF
+m horizon  +0
+a range    +0 +600		2 3   1
+a contact  +0 +420		2 3   ${THROUGHPUT}
+a contact  +0 +600		3 2   ${THROUGHPUT}
+EOF
 
-cd ../2.bench.ltp
-bpdriver 100000 ipn:2.1 ipn:3.1 -1000 &
+	echo "#########################################################################"
+	echo "##  Starting ION Nodes"
+	echo "#########################################################################"
+	echo
 
-# Wait for transmission to finish.
-echo "Waiting for transmission to finish..."
-RUNNING=1
-TIMER=0
-while [ $RUNNING -eq 1 ]
-do
-	TIMER=$((++TIMER))
-	sleep 1
-	echo "...receiving..."
-	# some ps don't like -p syntax, most do.
-	if [ $1 == "windows" ]
+	# Start nodes.
+	(cd 2.bench.ltp; ./ionstart)
+	(cd 3.bench.ltp; ./ionstart)
+
+	TESTNUM=0
+	for BUNDLESIZE in ${BUNDLESIZES}; do
+		let "++TESTNUM"
+		let "NUMBUNDLES = TOTALBYTES/BUNDLESIZE"
+		if [ $NUMBUNDLES -lt 1 ]; then
+			NUMBUNDLES=1
+			echo "Adjusting to $NUMBUNDLES of size $BUNDLESIZE"
+		elif [ $NUMBUNDLES -gt $MAXBUNDLES ]; then
+			echo "Truncating to $MAXBUNDLES of size $BUNDLESIZE (instead of $NUMBUNDLES)"
+			NUMBUNDLES=$MAXBUNDLES
+		fi
+		let "ACTUALBYTES = NUMBUNDLES*BUNDLESIZE"
+
+		sleep 1
+
+		cat << ==EOF==
+===============================================================================================================================
+RUNNING: Iteration ${ITERNUM}: Test ${TESTNUM}: ${NUMBUNDLES} bundles of ${BUNDLESIZE} bytes each - ${ACTUALBYTES} total bytes - Contact Plan MaxThroughput: ${THROUGHPUT} 
+===============================================================================================================================
+==EOF==
+		
+		cd 3.bench.ltp
+		bpcounter ipn:3.1 ${NUMBUNDLES} &
+		BPCOUNTER_PID=$!
+		cd ..
+		sleep 1
+
+		# if bpcounter didn't start, then something went wrong and we definitely haven't passsed!
+		# some ps don't like -p syntax, most do.
+		if [ "$1" == "windows" ]
+		then
+				ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+		else
+				ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+		fi
+		if [ $RETURN_VALUE -eq 0 ]
+		then
+			echo "bpcounter couldn't be started."
+			echo "...benchmarking terminated."
+			exit 1
+		fi
+
+		# bpdriver sends the bundles in the background
+		(cd 2.bench.ltp; bpdriver ${NUMBUNDLES} ipn:2.1 ipn:3.1 -${BUNDLESIZE} > /dev/null) &
+		BPDRIVER_PID=$!
+
+		# Wait for transmission to finish.
+		echo "Waiting for transmission to finish..."
+		RUNNING=1
+		TIMER=0
+		while [ $RUNNING -eq 1 ]
+		do
+			TIMER=$((++TIMER))
+			sleep 1
+			echo "...receiving..."
+			# some ps don't like -p syntax, most do.
+			if [ "$1" == "windows" ]
+			then
+				ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+			else
+				ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+			fi
+			if [ $RETURN_VALUE -eq 0 ]
+			then
+				echo "...transmission finished."
+				RUNNING=0
+			fi
+			if [ $TIMER -gt $MAXSECONDS ]
+			then
+				#infinite loop protection
+				echo "...$MAXSECONDS seconds passed; giving up."
+				RUNNING=0
+				RETVAL=1
+			fi
+		done
+
+		if [ $RETVAL -eq 1 ]
+		then
+			echo "Test did not complete."
+			echo "Killing bpcounter..."
+			kill -9 $BPCOUNTER_PID $BPDRIVER_PID
+			sleep 10
+			echo "Stopping ION..."
+			(cd 2.bench.ltp; ./ionstop) &
+			(cd 3.bench.ltp; ./ionstop) &
+			sleep 10
+			killm
+			sleep 10
+			echo "Re-starting ION..."
+			(cd 2.bench.ltp; ./ionstart)
+			(cd 3.bench.ltp; ./ionstart)
+			RETVAL=0;   # allow next test to proceed
+		fi
+
+	# loop to next bundle size
+	done
+
+	# loop to next contact plan throughput
+	done
+
+	# loop to next iteration
+	done
+
+	echo "#########################################################################"
+	echo "  Test has completed"
+	echo "#########################################################################"
+	if [ $RETVAL -eq 1 ]
 	then
-		ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
-	else
-		ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+		echo "Test did not complete correctly."
 	fi
-	if [ $RETURN_VALUE -eq 0 ]
-	then
-		echo "...transmission finished."
-		RUNNING=0
-	fi
-	if [ $TIMER -gt 300 ]
-	then
-		#infinite loop protection
-		echo "...5 minutes passed; giving up."
-		RUNNING=0
-		RETVAL=1
-	fi
-done
 
-if [ $RETVAL -eq 1 ]
-then
-	echo "Test did not complete."
 	echo "Stopping ION..."
-	cd ../2.bench.ltp
-	./ionstop &
-	cd ../3.bench.ltp
-	./ionstop &
-	sleep 5
-	killm
-	echo "...benchmarking terminated."
-	exit $RETVAL
-fi
-
-sleep 3
-echo ""
-echo "Test 2: 10000 bundles of 10,000 bytes each."
-cd ../3.bench.ltp
-bpcounter ipn:3.2 10000 &
-BPCOUNTER_PID=$!
-sleep 1
-
-cd ../2.bench.ltp
-bpdriver 10000 ipn:2.1 ipn:3.2 -10000 &
-
-# Wait for transmission to finish.
-echo "Waiting for transmission to finish..."
-RUNNING=1
-TIMER=0
-while [ $RUNNING -eq 1 ]
-do
-	TIMER=$((++TIMER))
-	sleep 1
-	echo "...receiving..."
-	# some ps don't like -p syntax, most do.
-	if [ $1 == "windows" ]
-	then
-		ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
-	else
-		ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
-	fi
-	if [ $RETURN_VALUE -eq 0 ]
-	then
-		echo "...transmission finished."
-		RUNNING=0
-	fi
-	if [ $TIMER -gt 300 ]
-	then
-		#infinite loop protection
-		echo "...5 minutes passed; giving up."
-		RUNNING=0
-		RETVAL=1
-	fi
-done
-
-if [ $RETVAL -eq 1 ]
-then
-	echo "Test did not complete."
-	echo "Stopping ION..."
-	cd ../2.bench.ltp
-	./ionstop &
-	cd ../3.bench.ltp
-	./ionstop &
-	sleep 5
-	killm
-	echo "...benchmarking terminated."
-	exit $RETVAL
-fi
-
-sleep 3
-echo ""
-echo "Test 3: 1000 bundles of 63,800 bytes each."
-cd ../3.bench.ltp
-bpcounter ipn:3.3 1000 &
-BPCOUNTER_PID=$!
-sleep 1
-
-cd ../2.bench.ltp
-bpdriver 1000 ipn:2.1 ipn:3.3 -63800 &
-
-# Wait for transmission to finish.
-echo "Waiting for transmission to finish..."
-RUNNING=1
-TIMER=0
-while [ $RUNNING -eq 1 ]
-do
-	TIMER=$((++TIMER))
-	sleep 1
-	echo "...receiving..."
-	# some ps don't like -p syntax, most do.
-	if [ $1 == "windows" ]
-	then
-		ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
-	else
-		ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
-	fi
-	if [ $RETURN_VALUE -eq 0 ]
-	then
-		echo "...transmission finished."
-		RUNNING=0
-	fi
-	if [ $TIMER -gt 300 ]
-	then
-		#infinite loop protection
-		echo "...5 minutes passed; giving up."
-		RUNNING=0
-		RETVAL=1
-	fi
-done
-
-if [ $RETVAL -eq 1 ]
-then
-	echo "Test did not complete."
-	echo "Stopping ION..."
-	cd ../2.bench.ltp
-	./ionstop &
-	cd ../3.bench.ltp
-	./ionstop &
-	sleep 5
-	killm
-	echo "...benchmarking terminated."
-	exit $RETVAL
-fi
-
-sleep 3
-echo ""
-echo "Test 4: 100 bundles of 1,000,000 bytes each."
-cd ../3.bench.ltp
-bpcounter ipn:3.4 100 &
-BPCOUNTER_PID=$!
-sleep 1
-
-cd ../2.bench.ltp
-bpdriver 100 ipn:2.1 ipn:3.4 -1000000 &
-
-# Wait for transmission to finish.
-echo "Waiting for transmission to finish..."
-RUNNING=1
-TIMER=0
-while [ $RUNNING -eq 1 ]
-do
-	TIMER=$((++TIMER))
-	sleep 1
-	echo "...receiving..."
-	# some ps don't like -p syntax, most do.
-	if [ $1 == "windows" ]
-	then
-		ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
-	else
-		ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
-	fi
-	if [ $RETURN_VALUE -eq 0 ]
-	then
-		echo "...transmission finished."
-		RUNNING=0
-	fi
-	if [ $TIMER -gt 300 ]
-	then
-		#infinite loop protection
-		echo "...5 minutes passed; giving up."
-		RUNNING=0
-		RETVAL=1
-	fi
-done
-
-if [ $RETVAL -eq 1 ]
-then
-	echo "Test did not complete."
-	echo "Stopping ION..."
-	cd ../2.bench.ltp
-	./ionstop &
-	cd ../3.bench.ltp
-	./ionstop &
-	sleep 5
-	killm
-	echo "...benchmarking terminated."
-	exit $RETVAL
-fi
-
-sleep 3
-echo ""
-echo "Test 5: 10 bundles of 10,000,000 bytes each."
-cd ../3.bench.ltp
-bpcounter ipn:3.5 10 &
-BPCOUNTER_PID=$!
-sleep 1
-
-cd ../2.bench.ltp
-bpdriver 10 ipn:2.1 ipn:3.5 -10000000 &
-
-# Wait for transmission to finish.
-echo "Waiting for transmission to finish..."
-RUNNING=1
-TIMER=0
-while [ $RUNNING -eq 1 ]
-do
-	TIMER=$((++TIMER))
-	sleep 1
-	echo "...receiving..."
-	# some ps don't like -p syntax, most do.
-	if [ $1 == "windows" ]
-	then
-		ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
-	else
-		ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
-	fi
-	if [ $RETURN_VALUE -eq 0 ]
-	then
-		echo "...transmission finished."
-		RUNNING=0
-	fi
-	if [ $TIMER -gt 300 ]
-	then
-		#infinite loop protection
-		echo "...5 minutes passed; giving up."
-		RUNNING=0
-		RETVAL=1
-	fi
-done
-
-if [ $RETVAL -eq 1 ]
-then
-	echo "Test did not complete."
-	echo "Stopping ION..."
-	cd ../2.bench.ltp
-	./ionstop &
-	cd ../3.bench.ltp
-	./ionstop &
-	sleep 5
-	killm
-	echo "...benchmarking terminated."
-	exit $RETVAL
-fi
-
-sleep 3
-echo ""
-echo "Test 6: 1 bundle of 100,000,000 bytes."
-cd ../3.bench.ltp
-bpcounter ipn:3.6 1 &
-BPCOUNTER_PID=$!
-sleep 1
-
-cd ../2.bench.ltp
-bpdriver 1 ipn:2.1 ipn:3.6 -100000000 &
-
-#Wait for transmission to finish.
-echo "Waiting for transmission to finish..."
-RUNNING=1
-TIMER=0
-while [ $RUNNING -eq 1 ]
-do
-	TIMER=$((++TIMER))
-	sleep 1
-	echo "...receiving..."
-	# some ps don't like -p syntax, most do.
-	if [ $1 == "windows" ]
-	then
-		ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
-	else
-		ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
-	fi
-	if [ $RETURN_VALUE -eq 0 ]
-	then
-		echo "...transmission finished."
-		RUNNING=0
-	fi
-	if [ $TIMER -gt 300 ]
-	then
-		#infinite loop protection
-		echo "...5 minutes passed; giving up."
-		RUNNING=0
-		RETVAL=1
-	fi
-done
-
-#if [ $RETVAL -eq 1 ]
-#then
-#echo "Test did not complete."
-#echo "Stopping ION..."
-#cd ../2.bench.ltp
-#./ionstop &
-#cd ../3.bench.ltp
-#./ionstop &
-#sleep 5
-#killm
-#echo "...benchmarking terminated."
-#exit $RETVAL
-#fi
-
-#sleep 3
-#echo ""
-#echo "Test 7: 1 bundle of 1,000,000,000 bytes."
-#cd ../3.bench.ltp
-#bpcounter ipn:3.7 1 &
-#BPCOUNTER_PID=$!
-#sleep 1
-#
-#cd ../2.bench.ltp
-#bpdriver 1 ipn:2.1 ipn:3.7 -1000000000 &
-#
-##Wait for transmission to finish.
-#echo "Waiting for transmission to finish..."
-#RUNNING=1
-#TIMER=0
-#while [ $RUNNING -eq 1 ]
-#do
-#TIMER=$((++TIMER))
-#sleep 1
-#echo "...receiving..."
-## some ps don't like -p syntax, most do.
-#if [ $1 == "windows" ]
-#then
-#ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
-#else
-#ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
-#fi
-#if [ $RETURN_VALUE -eq 0 ]
-#then
-#echo "...transmission finished."
-#RUNNING=0
-#fi
-#if [ $TIMER -gt 300 ]
-#then
-##infinite loop protection
-#echo "...5 minutes passed; giving up."
-#RUNNING=0
-#RETVAL=1
-#fi
-#done
-
-if [ $RETVAL -eq 1 ]
-then
-	echo "Test did not complete."
-fi
-
-echo "Stopping ION..."
-cd ../2.bench.ltp
-./ionstop &
-cd ../3.bench.ltp
-./ionstop &
-sleep 8
+	(cd 2.bench.ltp; ./ionstop) &
+	(cd 3.bench.ltp; ./ionstop) &
+	wait
+	wait
 killm
+
 echo "...benchmarking terminated."
 exit $RETVAL
