Adding check for bpv6 before looking for acsadmin. Updating runtests to run tests in the demos directory as well.

diff --git a/tests/bping/dotest b/tests/bping/dotest
--- a/tests/bping/dotest
+++ b/tests/bping/dotest
@@ -3,17 +3,24 @@
 # Tests that bping produces expected output and behaves well.
 #
 # documentation boilerplate
-echo "Looking for acsadmin"
-which acsadmin
-if [ $? -eq 0 ] ; then
-	echo "Found acsadmin"
-	ACS="found"
-	CONFIGFILES=" \
-	${CONFIGSROOT}/loopback-udp/loopback-acs.rc \
-	"
+ACS=""
+if [[ $BP_VERSION == "bpv6" ]] ; then
+	echo "Looking for acsadmin"
+	which acsadmin
+	if [ $? -eq 0 ] ; then
+		echo "Found acsadmin"
+		ACS="found"
+		CONFIGFILES=" \
+		${CONFIGSROOT}/loopback-udp/loopback-acs.rc \
+		"
+	else
+		echo "acsadmin not found"
+		ACS="missing"
+		CONFIGFILES=" \
+		${CONFIGSROOT}/loopback-udp/loopback.rc \
+		"
+	fi
 else
-	echo "acsadmin not found"
-	ACS="missing"
 	CONFIGFILES=" \
 	${CONFIGSROOT}/loopback-udp/loopback.rc \
 	"
@@ -67,7 +74,7 @@ rm -f ion.log bpingoutput1 bpingoutput2 bpingoutput3 bpingoutput4
 echo "Starting ION..."
 srcdir=`pwd`
 CONFIGDIR="${CONFIGSROOT}/loopback-udp"
-if [ $ACS == "found" ] ; then
+if [[ $ACS == "found" ]] ; then
 	echo "ionstart -I ${CONFIGDIR}/loopback-acs.rc"
 	"ionstart" -I "${CONFIGDIR}/loopback-acs.rc"
 else
diff --git a/tests/contact-volume/udp-loopback/dotest b/tests/contact-volume/udp-loopback/dotest
--- a/tests/contact-volume/udp-loopback/dotest
+++ b/tests/contact-volume/udp-loopback/dotest
@@ -4,20 +4,23 @@
 #
 # Written by Sebastian Kuzminsky, based on loopbacktest.sh by David Young
 #
-echo "Looking for acsadmin"
-which acsadmin
-if [ $? -eq 0 ] ; then
-	echo "Found acsadmin"
-	ACS="found"
-	CONFIGFILES=" \
-	${CONFIGSROOT}/loopback-udp/loopback-acs.rc \
-	"
-else
-	echo "acsadmin not found"
-	ACS="missing"
-	CONFIGFILES=" \
-	${CONFIGSROOT}/loopback-udp/loopback.rc \
-	"
+ACS=""
+if [[ $BP_VERSION == "bpv6" ]] ; then
+	echo "Looking for acsadmin"
+	which acsadmin
+	if [ $? -eq 0 ] ; then
+		echo "Found acsadmin"
+		ACS="found"
+		CONFIGFILES=" \
+		${CONFIGSROOT}/loopback-udp/loopback-acs.rc \
+		"
+	else
+		echo "acsadmin not found"
+		ACS="missing"
+		CONFIGFILES=" \
+		${CONFIGSROOT}/loopback-udp/loopback.rc \
+		"
+	fi
 fi
 echo "########################################"
 echo
@@ -49,7 +52,7 @@ IONRECEIVEFILE=./ionreceivefile.txt
 EXPECTEDCOUNT=9
 
 echo "Starting ION..."
-if [ $ACS == "found" ] ; then
+if [[ $ACS == "found" ]] ; then
 	echo "ionstart -I ${CONFIGSROOT}/loopback-udp/loopback-acs.rc"
 	"ionstart" -I "${CONFIGSROOT}/loopback-udp/loopback-acs.rc"
 else
