Updating tests to use new start up routines

diff --git a/tests/bug-0001-cgr-loopback/dotest b/tests/bug-0001-cgr-loopback/dotest
--- a/tests/bug-0001-cgr-loopback/dotest
+++ b/tests/bug-0001-cgr-loopback/dotest
@@ -53,10 +53,29 @@ RETVAL=0
 # Start nodes.
 cd 3.ipn.ltp
 ./ionstart
-sleep 10
+../../../system_up -i "p 30" -l "p 30" -b "p 30"
+
+if [ $? -eq 3 ]
+then
+	echo ""
+else
+	echo "Node 3 not started: Aborting Test"
+	exit 0
+fi
+
 cd ../2.ipn.ltp
 ./ionstart
-sleep 5
+../../../system_up -i "p 30" -l "p 30" -b "p 30"
+
+if [ $? -eq 3 ]
+then
+	echo ""
+else
+	echo "Node 2 not started: Aborting Test"
+	exit 0
+fi
+
+
 
 # Start bpecho on node 3.
 cd ../3.ipn.ltp
diff --git a/tests/issue-264-ltp-blksize/dotest b/tests/issue-264-ltp-blksize/dotest
--- a/tests/issue-264-ltp-blksize/dotest
+++ b/tests/issue-264-ltp-blksize/dotest
@@ -51,7 +51,28 @@ cd 2.ipn.ltp
 cd ../3.ipn.ltp
 ./ionstart >& node3.stdout
 
-sleep 10
+cd ../2.ipn.ltp
+../../../system_up -i "p 30" -l "p 30" -b "p 30"
+
+if [ $? -eq 3 ]
+then
+	echo ""
+else
+	echo "Node 2 not started: Aborting Test"
+	exit 0
+fi
+
+cd ../3.ipn.ltp
+../../../system_up -i "p 30" -l "p 30" -b "p 30"
+
+if [ $? -eq 3 ]
+then
+	echo ""
+else
+	echo "Node 3 not started: Aborting Test"
+	exit 0
+fi
+
 echo "Starting bprecvfile on node 3..."
 bprecvfile ipn:3.1 &
 cd ../2.ipn.ltp
diff --git a/tests/issue-276-loopback-range/dotest b/tests/issue-276-loopback-range/dotest
--- a/tests/issue-276-loopback-range/dotest
+++ b/tests/issue-276-loopback-range/dotest
@@ -40,6 +40,15 @@ export ION_NODE_LIST_DIR=$PWD
 
 # Start node 9, with 20-second loopback range.
 ./ionstart
+../../system_up -i "p 30" -l "p 30" -b "p 30"
+
+if [ $? -eq 3 ]
+then
+	echo ""
+else
+	echo "Node not started: Aborting Test"
+	exit 0
+fi
 
 # Send a loopback bundle with lifetime = 300.
 echo "Sending 10-byte bundle with 5-minute lifetime from ipn:9.1 to ipn:9.2."
diff --git a/tests/issue-313-overlapping-memcpy/dotest b/tests/issue-313-overlapping-memcpy/dotest
--- a/tests/issue-313-overlapping-memcpy/dotest
+++ b/tests/issue-313-overlapping-memcpy/dotest
@@ -66,7 +66,16 @@ rm -f ./ion_nodes
 cd 1.ipn.bp.ltp.udp
 ./ionstart > node.stdout
 
-sleep 10
+../../../system_up -i "p 30" -l "p 30" -b "p 30"
+
+if [ $? -eq 3 ]
+then
+	echo ""
+else
+	echo "Node not started: Aborting Test"
+	exit 0
+fi
+
 
 echo ""
 echo "Test 1---Use bpdriver and bpcounter to send a bunch of bundles and check log for error messages"
diff --git a/tests/issue-319-parseSocketSpec/ionstart b/tests/issue-319-parseSocketSpec/ionstart
--- a/tests/issue-319-parseSocketSpec/ionstart
+++ b/tests/issue-319-parseSocketSpec/ionstart
@@ -1,15 +1,25 @@
 # shell script to get node running
 #!/bin/bash
 ionadmin	amroc.ionrc
-sleep 1
-ionadmin	global.ionrc
-sleep 1
-ionsecadmin	amroc.ionsecrc
-sleep 1
-ltpadmin	amroc.ltprc
-sleep 1
-bpadmin		amroc.bprc
-sleep 1
+
+ionadmin	global.ionrc &
+
+ionsecadmin	amroc.ionsecrc &
+
+ltpadmin	amroc.ltprc &
+
+bpadmin		amroc.bprc &
+
+../../system_up -i "p 30" -l "p 30" -b "p 30"
+
+if [ $? -eq 3 ]
+then
+	echo ""
+else
+	echo "Node not started: Aborting Test"
+	exit 0
+fi
+
 amsd mib.amsrc @ amsdemo test "" &
 echo "Waiting for AMS cell census (90 seconds left)..."
 sleep 30
diff --git a/tests/issue-325-329-critical/dotest b/tests/issue-325-329-critical/dotest
--- a/tests/issue-325-329-critical/dotest
+++ b/tests/issue-325-329-critical/dotest
@@ -24,7 +24,52 @@ cd ../3.ipn.ltp
 cd ../4.ipn.ltp
 ./ionstart >& node4.stdout
 
-sleep 10
+cd ../1.ipn.ltp
+../../../system_up -i "p 30" -l "p 30" -b "p 30"
+
+if [ $? -eq 3 ]
+then
+	echo ""
+else
+	echo "Node 1 not started: Aborting Test"
+	exit 0
+fi
+
+cd ../2.ipn.ltp
+../../../system_up -i "p 30" -l "p 30" -b "p 30"
+
+if [ $? -eq 3 ]
+then
+	echo ""
+else
+	echo "Node 2 not started: Aborting Test"
+	exit 0
+fi
+
+cd ../3.ipn.ltp
+../../../system_up -i "p 30" -l "p 30" -b "p 30"
+
+if [ $? -eq 3 ]
+then
+	echo ""
+else
+	echo "Node 3 not started: Aborting Test"
+	exit 0
+fi
+
+cd ../4.ipn.ltp
+../../../system_up -i "p 30" -l "p 30" -b "p 30"
+
+if [ $? -eq 3 ]
+then
+	echo ""
+else
+	echo "Node 4 not started: Aborting Test"
+	exit 0
+fi
+
+#sleep 10
+
 echo "Starting bprecvfile on node 4..."
 bprecvfile ipn:4.1 &
 
diff --git a/tests/limbo/dotest b/tests/limbo/dotest
--- a/tests/limbo/dotest
+++ b/tests/limbo/dotest
@@ -64,10 +64,40 @@ RETVAL=0
 # Start nodes.
 cd 3.ipn.tcp
 ./ionstart
+../../../system_up -i "p 30" -b "p 30"
+
+if [ $? -eq 2 ]
+then
+	echo ""
+else
+	echo "Node 3 not started: Aborting Test"
+	exit 0
+fi
+
 cd ../5.ipn.tcp
 ./ionstart
+../../../system_up -i "p 30" -b "p 30"
+
+if [ $? -eq 2 ]
+then
+	echo ""
+else
+	echo "Node 5 not started: Aborting Test"
+	exit 0
+fi
+
 cd ../2.ipn.tcp
 ./ionstart
+../../../system_up -i "p 30" -b "p 30"
+
+if [ $? -eq 2 ]
+then
+	echo ""
+else
+	echo "Node 2 not started: Aborting Test"
+	exit 0
+fi
+
 echo "Sleeping 30 sec to give keepalive threads time to detect open sockets..."
 sleep 30
 
diff --git a/tests/ltp-purge/dotest b/tests/ltp-purge/dotest
--- a/tests/ltp-purge/dotest
+++ b/tests/ltp-purge/dotest
@@ -79,32 +79,62 @@ cd ../5.ipn.ltp
 ionadmin amroc.ionrc
 
 cd ../2.ipn.ltp
-ionadmin global.ionrc
+ionadmin global.ionrc &
 cd ../3.ipn.ltp
-ionadmin global.ionrc
+ionadmin global.ionrc &
 cd ../5.ipn.ltp
-ionadmin global.ionrc
+ionadmin global.ionrc &
 
 cd ../2.ipn.ltp
-ionsecadmin amroc.ionsecrc
+ionsecadmin amroc.ionsecrc &
 cd ../3.ipn.ltp
-ionsecadmin amroc.ionsecrc
+ionsecadmin amroc.ionsecrc &
 cd ../5.ipn.ltp
-ionsecadmin amroc.ionsecrc
+ionsecadmin amroc.ionsecrc &
 
 cd ../2.ipn.ltp
-ltpadmin amroc.ltprc
+ltpadmin amroc.ltprc &
 cd ../3.ipn.ltp
-ltpadmin amroc.ltprc
+ltpadmin amroc.ltprc &
 cd ../5.ipn.ltp
-ltpadmin amroc.ltprc
+ltpadmin amroc.ltprc &
 
 cd ../2.ipn.ltp
-bpadmin amroc.bprc
+bpadmin amroc.bprc &
 cd ../3.ipn.ltp
-bpadmin amroc.bprc
+bpadmin amroc.bprc &
 cd ../5.ipn.ltp
-bpadmin amroc.bprc
+bpadmin amroc.bprc &
+
+../../../system_up -i "p 30" -l "p 30" -b "p 30"
+
+if [ $? -eq 3 ]
+then
+	echo ""
+else
+	echo "Node 2 not started: Aborting Test"
+	exit 0
+fi
+
+../../../system_up -i "p 30" -l "p 30" -b "p 30"
+
+if [ $? -eq 3 ]
+then
+	echo ""
+else
+	echo "Node 3 not started: Aborting Test"
+	exit 0
+fi
+
+../../../system_up -i "p 30" -l "p 30" -b "p 30"
+
+if [ $? -eq 3 ]
+then
+	echo ""
+else
+	echo "Node 5 not started: Aborting Test"
+	exit 0
+fi
 
 # Start file receiver on node 5.
 echo "Starting bprecvfile..."
