tests: add system_up startup validation to prevent false-positive results

diff --git a/demos/bench-bssp/dotest b/demos/bench-bssp/dotest
--- a/demos/bench-bssp/dotest
+++ b/demos/bench-bssp/dotest
@@ -58,8 +58,23 @@ RETVAL=0
 # Start nodes.
 cd 2.bench.bssp
 ./ionstart
+../../../system_up -i "p 30" -b "p 30"
+if [ $? -eq 2 ]; then
+    echo ""
+else
+    echo "Node 2 not started: Aborting Test"
+    exit 1
+fi
+
 cd ../3.bench.bssp
 ./ionstart
+../../../system_up -i "p 30" -b "p 30"
+if [ $? -eq 2 ]; then
+    echo ""
+else
+    echo "Node 3 not started: Aborting Test"
+    exit 1
+fi
 
 sleep 5
 echo ""
diff --git a/demos/bench-cgr/dotest b/demos/bench-cgr/dotest
--- a/demos/bench-cgr/dotest
+++ b/demos/bench-cgr/dotest
@@ -64,12 +64,43 @@ RETVAL=0
 # Start nodes.
 cd 1.bench.stcp
 ./ionstart
+../../../system_up -i "p 30" -b "p 30"
+if [ $? -eq 2 ]; then
+    echo ""
+else
+    echo "Node 1 not started: Aborting Test"
+    exit 1
+fi
+
 cd ../2.bench.stcp
 ./ionstart
+../../../system_up -i "p 30" -b "p 30"
+if [ $? -eq 2 ]; then
+    echo ""
+else
+    echo "Node 2 not started: Aborting Test"
+    exit 1
+fi
+
 cd ../3.bench.stcp
 ./ionstart
+../../../system_up -i "p 30" -b "p 30"
+if [ $? -eq 2 ]; then
+    echo ""
+else
+    echo "Node 3 not started: Aborting Test"
+    exit 1
+fi
+
 cd ../4.bench.stcp
 ./ionstart
+../../../system_up -i "p 30" -b "p 30"
+if [ $? -eq 2 ]; then
+    echo ""
+else
+    echo "Node 4 not started: Aborting Test"
+    exit 1
+fi
 
 sleep 3
 echo ""
diff --git a/demos/bench-tcpv6/dotest b/demos/bench-tcpv6/dotest
--- a/demos/bench-tcpv6/dotest
+++ b/demos/bench-tcpv6/dotest
@@ -106,7 +106,18 @@ while [ "${ITERNUM}" -lt ${ITERATIONS} ]; do
 
     # Start nodes.
     (cd 2.bench.tcpv6; ./ionstart)
+    (cd 2.bench.tcpv6; ../../../system_up -i "p 30" -b "p 30")
+    if [ $? -ne 2 ]; then
+        echo "Node 2 not started: Aborting Test"
+        exit 1
+    fi
+
     (cd 3.bench.tcpv6; ./ionstart)
+    (cd 3.bench.tcpv6; ../../../system_up -i "p 30" -b "p 30")
+    if [ $? -ne 2 ]; then
+        echo "Node 3 not started: Aborting Test"
+        exit 1
+    fi
 
     TESTNUM=0
     for BUNDLESIZE in ${BUNDLESIZES}; do
@@ -183,7 +194,17 @@ RUNNING: Iteration ${ITERNUM}: Test ${TESTNUM}: ${NUMBUNDLES} bundles of ${BUNDL
         sleep 3
         echo "Re-starting ION..."
         (cd 2.bench.tcpv6; ./ionstart)
+        (cd 2.bench.tcpv6; ../../../system_up -i "p 30" -b "p 30")
+        if [ $? -ne 2 ]; then
+            echo "Node 2 not started after restart: Aborting Test"
+            exit 1
+        fi
         (cd 3.bench.tcpv6; ./ionstart)
+        (cd 3.bench.tcpv6; ../../../system_up -i "p 30" -b "p 30")
+        if [ $? -ne 2 ]; then
+            echo "Node 3 not started after restart: Aborting Test"
+            exit 1
+        fi
         RETVAL=0;   # allow next test to proceed
     fi
 
diff --git a/tests/bpsec/bpsec-policy-test/dotest b/tests/bpsec/bpsec-policy-test/dotest
--- a/tests/bpsec/bpsec-policy-test/dotest
+++ b/tests/bpsec/bpsec-policy-test/dotest
@@ -31,7 +31,13 @@ ionsecadmin amroc.ionsecrc
 ltpadmin amroc.ltprc
 bpadmin amroc.bprc
 bpsecadmin amroc.bpsecrc
-
+../../../../system_up -i "p 30" -l "p 30" -b "p 30"
+if [ $? -eq 3 ]; then
+    echo ""
+else
+    echo "Node 2 not started: Aborting Test"
+    exit 1
+fi
 
 cd ../3.ipn.ltp
 ionadmin amroc.ionrc
@@ -40,6 +46,13 @@ ionsecadmin amroc.ionsecrc
 ltpadmin amroc.ltprc
 bpadmin amroc.bprc
 bpsecadmin amroc.bpsecrc
+../../../../system_up -i "p 30" -l "p 30" -b "p 30"
+if [ $? -eq 3 ]; then
+    echo ""
+else
+    echo "Node 3 not started: Aborting Test"
+    exit 1
+fi
 
 cd ../4.ipn.ltp
 ionadmin amroc.ionrc
@@ -48,6 +61,13 @@ ionsecadmin amroc.ionsecrc
 ltpadmin amroc.ltprc
 bpadmin amroc.bprc
 bpsecadmin amroc.bpsecrc
+../../../../system_up -i "p 30" -l "p 30" -b "p 30"
+if [ $? -eq 3 ]; then
+    echo ""
+else
+    echo "Node 4 not started: Aborting Test"
+    exit 1
+fi
 
 cd ..
 
@@ -260,3 +280,4 @@ echo "Stopping ION..."
 
 killm
 echo -e "Status reports test completed.\n"
+exit 0
diff --git a/tests/sdr-no-dram/dotest b/tests/sdr-no-dram/dotest
--- a/tests/sdr-no-dram/dotest
+++ b/tests/sdr-no-dram/dotest
@@ -56,8 +56,23 @@ export ION_NODE_LIST_DIR=$PWD
 # Start nodes.
 cd 2.ipn.ltp
 ./ionstart >& node2.stdout
+../../../system_up -i "p 30" -l "p 30" -b "p 30"
+if [ $? -eq 3 ]; then
+    echo ""
+else
+    echo "Node 2 not started: Aborting Test"
+    exit 1
+fi
+
 cd ../3.ipn.ltp
 ./ionstart >& node3.stdout
+../../../system_up -i "p 30" -l "p 30" -b "p 30"
+if [ $? -eq 3 ]; then
+    echo ""
+else
+    echo "Node 3 not started: Aborting Test"
+    exit 1
+fi
 
 echo "Starting bpcounter on node 3..."
 sleep 1
