Update and enable bpdriver-ttl test to use bespokebpv7

diff --git a/tests/issue-265-bpdriver-ttl-option/dotest b/tests/issue-265-bpdriver-ttl-option/dotest
--- a/tests/issue-265-bpdriver-ttl-option/dotest
+++ b/tests/issue-265-bpdriver-ttl-option/dotest
@@ -1,25 +1,20 @@
 #!/usr/bin/env bash
 #
-# Samuel Jero
-# Ohio University
-# September 10, 2011
+# Nate Richard
+# JPL
+# April 1, 2026
 #
 # This test pertains to issue #265 "Create Bpdriver commandline option for ttl".
 # This test confirms that bpdriver can now send bundles with varying ttl values.
-# The test uses netcat to receive BP bundles.
 
 
 function end(){
-# Shut down ION processes.
-echo "Stopping ION..."
-#cd 1.ipn.bp.udp
-#./ionstop &
-#cd ../
-#sleep 5
-killm
-
-echo "bpdriver ttl option test complete."
-exit $RETVAL
+    echo
+    echo "Stopping ION..."
+    cd 1.ipn.bp.udp
+    ionexit
+    echo "bpdriver TTL test completed."
+    exit $RETVAL
 }
 
 CONFIGFILES=" \
@@ -33,7 +28,7 @@ pwd | sed "s/\/.*\///" | xargs echo "NAME: "
 echo
 echo "PURPOSE: Testing the functionality of issue 265.
         Confirms that bpdriver can now send bundles with varying ttl values.
-        This test uses netcat to receive BP bundles."
+        This test uses bespokebpv7 to receive BP bundles."
 echo
 echo "CONFIG: 1 node custom:"
 echo
@@ -48,205 +43,93 @@ echo "OUTPUT: Terminal messages will relay results."
 echo
 echo "########################################"
 
-./cleanup
+# Find the latest available Python 3 version >= 3.10
+PYTHON_CMD="python3"
+MAX_MINOR=-1
 
-# Check that prerequisite software for the test is installed
-PROGRAMTEST="netcat"
-OS=`uname`
-RESULTS=`which ${PROGRAMTEST}`
-WHICHRETURN=$?
-echo "${RESULTS}" | grep "^no ${PROGRAMTEST} in"
-WHICHFAILMESSAGE=$?
-# which could return the proper fail condition, or the results could be
-# empty, or you're on solaris and your results will be "no netcat in $PATH".
-if [ $WHICHRETURN -ne 0 -o -z "${RESULTS}" -o $WHICHFAILMESSAGE -eq 0 ] ; then
-    echo "${PROGRAMTEST} is not present in this system; skipping..."
+check_python_version() {
+    local py_exec=$1
+    if command -v "$py_exec" &> /dev/null; then
+        local py_maj=$("$py_exec" -c 'import sys; print(sys.version_info[0])' 2>/dev/null)
+        local py_min=$("$py_exec" -c 'import sys; print(sys.version_info[1])' 2>/dev/null)
+        if [ "$py_maj" = "3" ] && [ "$py_min" -ge 10 ]; then
+            if [ "$py_min" -gt "$MAX_MINOR" ]; then
+                MAX_MINOR=$py_min
+                PYTHON_CMD="$py_exec"
+            fi
+        fi
+    fi
+}
+
+# Check standard $PYTHON_CMD first
+check_python_version $PYTHON_CMD
+
+i=20
+while [ $i -ge 10 ]; do
+    check_python_version "$PYTHON_CMD.$i"
+    i=$((i - 1))
+done
+
+if [ -z "$PYTHON_CMD" ]; then
+    echo "SKIP: Python 3.10 or higher is required but not found."
     exit 2
-elif [ "$OS" = "SunOS" ]; then
-    echo "Using SunOS netcat at `which netcat`."
-else
-    echo "Using standard netcat at `which netcat`."
-
 fi
 
-sleep 1
-RETVAL=1
+PYTHON_VERSION="3.$MAX_MINOR"
+echo "Using Python $PYTHON_VERSION (via $PYTHON_CMD)"
+echo
 
+./cleanup
+RETVAL=1
 
 #Start ION
 echo "Starting ion node..."
 export ION_NODE_LIST_DIR=$PWD
-rm -f ./ion_nodes
 cd 1.ipn.bp.udp
 ./ionstart > node.stdout
-
-../../../system_up -i "p 30" -b "p 30"
-
-if [ $? -eq 2 ]
-then
-    echo ""
-else
-    echo "Node not started: Aborting Test"
-    exit 1
-fi
+echo
 
 cd ../
 
-# Run the platform-specific netcat server
-run_netcat() {
-    if [ "$OS" = "SunOS" ]; then
-        netcat -u -l -p 4556 > response.bpseg &
-        NETCAT_SVR_PID=$!
-    # GNU netcat has a -V (version) flag, so test for that.
-    elif netcat -V 2>/dev/null; then
-        netcat -u -l -p 4556 > response.bpseg &
-        NETCAT_SVR_PID=$!
-    # Fall back to BSD netcat
-    else
-        netcat -u -l 4556 > response.bpseg &
-        NETCAT_SVR_PID=$!
-    fi
-}
-
-#Test 1---default TTL (300sec)
-echo "Test 1---Check bpdriver default TTL (300 sec)"
-echo "Starting netcat server for test..."
-cd netcat_files/
-run_netcat
-cd ../
-
-echo "Using bpdriver to send bundles with default ttl..."
-cd 1.ipn.bp.udp
-bpdriver 1 ipn:1.1 ipn:1.2 -100
-cd ../
-
-echo "Waiting 2 seconds for netcat server to receive bundle..."
-sleep 2
-
-echo "Stopping netcat server..."
-kill -2 $NETCAT_SVR_PID >/dev/null 2>&1
-sleep 1
-kill -9 $NETCAT_SVR_PID >/dev/null 2>&1
-
-# assemble the packet to be readable by wireshark
-# 1.) Copy the lower layers of a precorded bundle
-# 2.) Append the BP layer from netcat
-cd netcat_files/
-cp lowerlayers response.cap
-cat response.bpseg >> response.cap
-
-# Now we analyze the TTL value from the BP header of the bundle. We measure
-# from the end of the bundle to avoid the SDNV timestamp field which will have
-# a constantly changing length.
-RESULTS=`cat response.cap | tail  -c123 | xxd -p -c 256 | cut -c 1-4 | tr -d '\n'`
-echo "Expected value: 822c"
-echo "  Actual value: $RESULTS"
-if [ "$RESULTS" = "822c" ]; then
-    echo "The Bundle set by ION had the correct default TTL."
-    echo ""
+# Test 1 --- Default TTL (300sec)
+echo "Test 1 --- Check bpdriver default TTL (300 sec)"
+python3 runtest.py 300 -p 4556
+if [ $? -eq 0 ]; then
+    echo "Test 1 SUCCESS"
+    echo
     RETVAL=0
 else
-    # We have a problem.  The BP response doesn't have the ttl we expect it to have.  Test failed.
-    echo "The Bundle sent by ION did not have the correct default TTL.  FAILURE!"
-    echo ""
+    echo "Test 1 FAILURE"
+    echo
     RETVAL=1
-    cd ..
     end
 fi
-cd ..
 
-
-#Test 2---Larger TTL (3000sec)
-echo "Test 2---Try Increasing bpdriver TTL (3000sec)"
-echo "Starting netcat server for test..."
-cd netcat_files/
-run_netcat
-cd ../
-
-echo "Using bpdriver to send bundles with ttl of 3000 sec..."
-cd 1.ipn.bp.udp
-bpdriver 1 ipn:1.1 ipn:1.2 -100 t3000
-cd ../
-
-echo "Waiting 2 seconds for netcat server to receive bundle..."
-sleep 2
-
-echo "Stopping netcat server..."
-kill -2 $NETCAT_SVR_PID >/dev/null 2>&1
-sleep 1
-kill -9 $NETCAT_SVR_PID >/dev/null 2>&1
-
-# assemble the packet to be readable by wireshark
-# 1.) Copy the lower layers of a precorded bundle
-# 2.) Append the BP layer from netcat
-cd netcat_files/
-cp lowerlayers response.cap
-cat response.bpseg >> response.cap
-
-# Now we analyze the TTL value from the BP header of the bundle. We measure
-# from the end of the bundle to avoid the SDNV timestamp field which will have
-# a constantly changing length.
-RESULTS=`cat response.cap | tail  -c121 | xxd -p -c 256 | cut -c 1-4 | tr -d '\n'`
-echo "Expected value: 9738"
-echo "  Actual value: $RESULTS"
-if [ "$RESULTS" = "9738" ]; then
-    echo "The Bundle set by ION had the correct TTL."
-    echo ""
+# Test 2 --- Larger TTL (3000sec)
+echo "Test 2 --- Try Increasing bpdriver TTL (3000sec)"
+python3 runtest.py 3000 -p 4556
+if [ $? -eq 0 ]; then
+    echo "Test 2 SUCCESS"
+    echo
     RETVAL=0
 else
-    # We have a problem.  The BP response doesn't have the ttl we expect it to have.  Test failed.
-    echo "The Bundle sent by ION did not have the correct TTL.  FAILURE!"
-    echo ""
+    echo "Test 2 FAILURE"
+    echo
     RETVAL=1
-    cd ..
     end
 fi
-cd ..
 
-
-#Test 3---Smaller TTL (30sec)
-echo "Test 3--Try Decreasing bpdriver TTL (30sec)"
-echo "Starting netcat server for test..."
-cd netcat_files/
-run_netcat
-cd ../
-
-echo "Using bpdriver to send bundles with ttl of 30 sec..."
-cd 1.ipn.bp.udp
-bpdriver 1 ipn:1.1 ipn:1.2 -100 t30
-cd ../
-
-echo "Waiting 2 seconds for netcat server to receive bundle..."
-sleep 2
-
-echo "Stopping netcat server..."
-kill -2 $NETCAT_SVR_PID >/dev/null 2>&1
-sleep 1
-kill -9 $NETCAT_SVR_PID >/dev/null 2>&1
-
-# assemble the packet to be readable by wireshark
-# 1.) Copy the lower layers of a precorded bundle
-# 2.) Append the BP layer from netcat
-cd netcat_files/
-cp lowerlayers response.cap
-cat response.bpseg >> response.cap
-
-# Now we analyze the TTL value from the BP header of the bundle. We measure
-# from the end of the bundle to avoid the SDNV timestamp field which will have
-# a constantly changing length.
-RESULTS=`cat response.cap | tail  -c120 | xxd -p -c 256 | cut -c 1-2 | tr -d '\n'`
-echo "Expected value: 1e"
-echo "  Actual value: $RESULTS"
-if [ "$RESULTS" = "1e" ]; then
-    echo "The Bundle set by ION had the correct TTL. SUCCESS!"
-    echo ""
+# Test 3 --- Smaller TTL (30sec)
+echo "Test 3 --- Try Decreasing bpdriver TTL (30sec)"
+python3 runtest.py 30 -p 4556
+if [ $? -eq 0 ]; then
+    echo "Test 3 SUCCESS"
+    echo
     RETVAL=0
 else
-    # We have a problem.  The BP response doesn't have the ttl we expect it to have.  Test failed.
-    echo "The Bundle sent by ION did not have the correct TTL.  FAILURE!"
-    echo ""
+    echo "Test 3 FAILURE"
+    echo
     RETVAL=1
 fi
-cd ..
 
 end
