Updating benchmark demos that need higher memory allocations on MacOS.

diff --git a/demos/bench-bibect/dotest b/demos/bench-bibect/dotest
--- a/demos/bench-bibect/dotest
+++ b/demos/bench-bibect/dotest
@@ -57,6 +57,14 @@ echo "***PLEASE NOTE: this benchmark test requires Bundle Protocol version 7."
 
 ./cleanup
 sleep 1
+
+echo "Checking for additional memory needed for this demo..."
+./check_memory 
+if [ $? != 0 ]; then
+	echo "Can't run, need additional system resources"
+	exit 1
+fi
+
 echo "Starting ION..."
 export ION_NODE_LIST_DIR=$PWD
 rm -f ./ion_nodes
@@ -77,6 +85,22 @@ cd ../4.bench.bibe
 bpcounter ipn:4.1 10 &
 BPCOUNTER_PID=$!
 sleep 1
+
+# if bpcounter didn't start, then something went wrong and we definitely haven't passsed!
+# some ps don't like -p syntax, most do.
+if [ $1 == "windows" ]
+then
+		ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+else
+		ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+fi
+if [ $RETURN_VALUE -eq 0 ]
+then
+	echo "bpcounter couldn't be started."
+	echo "...benchmarking terminated."
+	exit 1
+fi
+
 
 cd ../2.bench.bibe
 bptrace ipn:2.1 ipn:4.1 dtn:none 100 0.1.0.0.0.13 "Go."
diff --git a/demos/bench-dgr/dotest b/demos/bench-dgr/dotest
--- a/demos/bench-dgr/dotest
+++ b/demos/bench-dgr/dotest
@@ -47,6 +47,14 @@ echo "########################################"
 
 ./cleanup
 sleep 1
+
+echo "Checking for additional memory needed for this demo..."
+./check_memory 
+if [ $? != 0 ]; then
+	echo "Can't run, need additional system resources"
+	exit 1
+fi
+
 echo "Starting ION..."
 export ION_NODE_LIST_DIR=$PWD
 rm -f ./ion_nodes
@@ -65,6 +73,21 @@ cd ../3.bench.dgr
 bpcounter ipn:3.1 10000 &
 BPCOUNTER_PID=$!
 sleep 1
+
+# if bpcounter didn't start, then something went wrong and we definitely haven't passsed!
+# some ps don't like -p syntax, most do.
+if [ $1 == "windows" ]
+then
+		ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+else
+		ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+fi
+if [ $RETURN_VALUE -eq 0 ]
+then
+	echo "bpcounter couldn't be started."
+	echo "...benchmarking terminated."
+	exit 1
+fi
 
 cd ../2.bench.dgr
 bpdriver 10000 ipn:2.1 ipn:3.1 -1000 &
