update ipaddr re-resolve test for ltp

diff --git a/tests/ipaddr-caching-udplso/dotest b/tests/ipaddr-caching-udplso/dotest
--- a/tests/ipaddr-caching-udplso/dotest
+++ b/tests/ipaddr-caching-udplso/dotest
@@ -108,7 +108,8 @@ BACKUP_FILE="/tmp/hosts.bak"
 ENTRY="127.0.1.3    test3.local"
 LOG_FILE="ion.log"
 SEARCH_STRING1="udplso: initial DNS resolution failed for test3.local:3113"
-SEARCH_STRING2="udplso: Successfully resolved hostname: test3.local"
+SEARCH_STRING2="parseSocketSpec: Parsed: test3.local:3113"
+SEARCH_STRING3="(0) 0 0 (1) 6 42 (2) 0 0 (+) 6 42"
 LINE_NUM=1
 
 # Check for sudo availability
@@ -151,8 +152,6 @@ echo "Step 1: Destination host not in DNS database or hosts file."
 echo ""
 
 cd ../2.bench.ltp
-bpsource ipn:3.1 "Hello!"
-sleep 2
 
 # Check ion.log for DNS lookup report
 LINE_NUM=$(search_log_after_line "$LOG_FILE" "$SEARCH_STRING1" "$LINE_NUM")
@@ -180,24 +179,7 @@ else
     echo "Error: Failed to add entry '$ENTRY' to $HOSTS_FILE"
     exit 1
 fi
-
-# Sending several messages
-echo ""
-echo "Sending messages until hostname is re-resolved in 60 seconds..."
-bpsource ipn:3.1 "Hello2!"
 sleep 10
-bpsource ipn:3.1 "Hello3!"
-sleep 10
-bpsource ipn:3.1 "Hello4!"
-sleep 10
-bpsource ipn:3.1 "Hello5!"
-sleep 10
-bpsource ipn:3.1 "Hello6!"
-sleep 10
-bpsource ipn:3.1 "Hello7!"
-sleep 10
-
-echo "The last bundle should succeed - assuming re-resolve timer is set for 60 seconds."
 
 # Check ion.log for DNS lookup report
 LINE_NUM=$(search_log_after_line "$LOG_FILE" "$SEARCH_STRING2" "$LINE_NUM")
@@ -208,6 +190,50 @@ else
 	echo "FAIL: No match or error (return code: -1)"
 	RETVAL=1
 fi
+
+# Step 3: Sending LTP data
+echo ""
+echo "Step 3: Sending LTP data"
+echo ""
+
+# Sending several messages
+echo ""
+echo "Sending messages to verify hostname is resolved..."
+bpsource ipn:3.1 "Hello1!"
+bpsource ipn:3.1 "Hello2!"
+bpsource ipn:3.1 "Hello3!"
+bpsource ipn:3.1 "Hello4!"
+bpsource ipn:3.1 "Hello5!"
+bpsource ipn:3.1 "Hello6!"
+sleep 10
+
+bpstats
+sleep 3
+echo ""
+echo "Confirm the transmission..."
+echo ""
+cat ion.log | grep xmt
+
+echo ""
+echo "Now check the receiver to confirm reception..."
+echo ""
+
+cd ../3.bench.ltp
+bpstats
+sleep 3
+
+cat ion.log | grep rcv 
+
+# Check ion.log for DNS lookup report
+LINE_NUM=$(search_log_after_line "$LOG_FILE" "$SEARCH_STRING3" "$LINE_NUM")
+return_code=$?
+if [ $return_code -eq 0 ]; then
+	echo "SUCCESS: ion.log confirm data reception at line: $LINE_NUM"
+else
+	echo "FAIL: No match or error (return code: -1)"
+	RETVAL=1
+fi
+
 
 if [ "$RETVAL" -eq 1 ]
 then
