Setting Python min version to 3.9
3.9 is already EOL, but it is the bare minimum need to support this test.

diff --git a/tests/conformance_test/dotest b/tests/conformance_test/dotest
--- a/tests/conformance_test/dotest
+++ b/tests/conformance_test/dotest
@@ -53,8 +53,8 @@ fi
 PYTHON_VERSION=$(python3 -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')
 PYTHON_MAJOR=$(python3 -c 'import sys; print(sys.version_info[0])')
 PYTHON_MINOR=$(python3 -c 'import sys; print(sys.version_info[1])')
-if [ "$PYTHON_MAJOR" -lt 3 ] || { [ "$PYTHON_MAJOR" -eq 3 ] && [ "$PYTHON_MINOR" -lt 6 ]; }; then
-    echo "Error: Python 3.6 or higher is required. Found version $PYTHON_VERSION"
+if [ "$PYTHON_MAJOR" -lt 3 ] || { [ "$PYTHON_MAJOR" -eq 3 ] && [ "$PYTHON_MINOR" -lt 9 ]; }; then
+    echo "Error: Python 3.9 or higher is required. Found version $PYTHON_VERSION"
     exit 1
 fi
 echo "Using Python $PYTHON_VERSION"
