Set trigger control to admin

diff --git a/.github/workflows/ci-run-PR-tests.yml b/.github/workflows/ci-run-PR-tests.yml
--- a/.github/workflows/ci-run-PR-tests.yml
+++ b/.github/workflows/ci-run-PR-tests.yml
@@ -4,6 +4,14 @@ on:
   workflow_dispatch:  # Manual trigger only
 
 jobs:
+  check-user:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Restrict Trigger Access
+        if: "!contains(fromJson('[\"iondev33\", \"type6six\"]'), github.actor)"
+        run: |
+          echo "Error: User ${{ github.actor }} is not authorized to trigger this workflow."
+          exit 1
   ubuntu-latest:
     uses: ./.github/workflows/ci-workflow-ubuntu.yml
 
