update workflow

diff --git a/.github/workflows/ci-workflow-freeBSD14.yml b/.github/workflows/ci-workflow-freeBSD14.yml
--- a/.github/workflows/ci-workflow-freeBSD14.yml
+++ b/.github/workflows/ci-workflow-freeBSD14.yml
@@ -4,17 +4,16 @@ on:
   pull_request:
     branches:
       - integration
-
   workflow_dispatch:
-
-#  push:
-#    branches:
-#      - update-4.1.4-freebsd-update
+    inputs:
+      tests_to_run:
+        description: 'Space-separated list of tests to run (e.g., "test1 test2"). Leave blank to run all.'
+        required: false
+        default: ''
 
 jobs:
   build-and-test:
     runs-on: [self-hosted, linux, x64, karuna]
-
     steps:
       - name: Clean up workspace
         run: |
@@ -37,7 +36,8 @@ jobs:
 
       - name: Display VM OS and Arch
         run: |
-          ssh -o StrictHostKeyChecking=no jgao@$VM_IP 'cat /etc/os-release && 
+          ssh -o StrictHostKeyChecking=no jgao@$VM_IP '
+            cat /etc/os-release && 
             echo "Arch:" && 
             uname -m &&
             echo "User ID:" &&
@@ -48,37 +48,20 @@ jobs:
         run: |
           ssh -o StrictHostKeyChecking=no jgao@$VM_IP 'rm -rf ~/ion-gh-test-dir && mkdir -p ~/ion-gh-test-dir'
           scp -o StrictHostKeyChecking=no -r "$GITHUB_WORKSPACE" jgao@$VM_IP:~/ion-gh-test-dir
-          
-      # assume dependencies are already satisfied
-      #- name: Set up dependencies in VM
-      #  run: |
-      #      ssh -o StrictHostKeyChecking=no jgao@$VM_IP 'pkg update &&
-      #        sudo pkg install -y autoconf automake libtool bash python3 gcc make psmisc wget'
-      
-      # assume Mbedtls is already installed
-      #- name: Install MBEDTLS 2.28.9 in VM
-      #  run: |
-      #      wget https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/mbedtls-2.28.9.tar.gz
-      #      tar -zvxf mbedtls-2.28.9.tar.gz
-      #      cd mbedtls-mbedtls-2.28.9/
-      #      sed -i '/#define MBEDTLS_NIST_KW_C/s/\/\///' "./include/mbedtls/config.h"
-      #      make SHARED=1
-      #      make check
-      #      make install
 
       - name: Generate timestamp for file names
         id: timestamp
         run: echo "TIMESTAMP=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
 
       - name: Run build and tests, capture stdout
-        run: | # For now run only test starting with "b", redirect stdout and stderr to a log
+        run: |
           ssh -o StrictHostKeyChecking=no jgao@$VM_IP '
             echo "Starting build and tests at $(date)" &&
-            export USER=$(whoami)  # Set USER to the current username &&
+            export USER=$(whoami) &&
             echo "USER is set to: $USER" &&
             export ION_RUN_EXPERT="yes" &&
             export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH &&
-            cd ~/ion-gh-test-dir/ion-ios-dev
+            cd ~/ion-gh-test-dir/ion-ios-dev &&
             autoreconf -fi &&
             ./configure --enable-crypto-mbedtls --enable-bpsec-debugging &&
             gmake -j4 &&
@@ -86,39 +69,43 @@ jobs:
             gmake buildcheck &&
             sudo ldconfig &&
             cd tests &&
-            ./runtests' > build-and-test.log 2>&1
+            if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.tests_to_run }}" ]; then
+              echo "Running specific tests: ${{ github.event.inputs.tests_to_run }}" &&
+              ./runtests ${{ github.event.inputs.tests_to_run }}
+            else
+              echo "Running all tests" &&
+              ./runtests
+            fi' > build-and-test.log 2>&1
 
       - name: Display Progress
-        if: ${{ always() }}  # Display progress even if tests were interrupted
-        run: | 
+        if: ${{ always() }}
+        run: |
           ssh -o StrictHostKeyChecking=no jgao@$VM_IP '
             cat ~/ion-gh-test-dir/ion-ios-dev/tests/progress' > progress
-          cat progress | grep "FAILED" || { printf "No failed tests. \n"; exit 0; }
+          cat progress | grep "FAILED" || { printf "No failed tests.\n"; exit 0; }
 
       - name: Upload full build and test log
-        if: ${{ always() }}  # Capture log even if the previous step fails
+        if: ${{ always() }}
         uses: actions/upload-artifact@v4
         with:
           name: build-and-test-log-${{ env.TIMESTAMP }}
-          path: build-and-test.log  # Upload the entire stdout and stderr as an artifact
+          path: build-and-test.log
 
       - name: Upload progress file as artifact
-        if: ${{ always() }}  # Capture progress even if the previous step fails
+        if: ${{ always() }}
         uses: actions/upload-artifact@v4
         with:
           name: test-progress-${{ env.TIMESTAMP }}
-          path: ./progress  # Upload the 'progress' file for later review
+          path: ./progress
 
       - name: Clean up ION build
-        if: ${{ always() }}  # Clean up even if previous steps fails
+        if: ${{ always() }}
         run: |
           ssh -o StrictHostKeyChecking=no jgao@$VM_IP '
-          killm
-          cd ~/ion-gh-test-dir/ion-ios-dev &&
-          sudo gmake uninstall &&
-          gmake clean &&
-          cd ../.. &&
-          rm -rf ~/ion-gh-test-dir'  # Uninstall/clean ION from FreeBSD VM 
-          rm -rf $GITHUB_WORKSPACE/* # Remove workspace content from host runner
-
-
+            killm &&
+            cd ~/ion-gh-test-dir/ion-ios-dev &&
+            sudo gmake uninstall &&
+            gmake clean &&
+            cd ../.. &&
+            rm -rf ~/ion-gh-test-dir'
+          rm -rf $GITHUB_WORKSPACE/*
diff --git a/.github/workflows/ci-workflow-macos_14_7.yml b/.github/workflows/ci-workflow-macos_14_7.yml
--- a/.github/workflows/ci-workflow-macos_14_7.yml
+++ b/.github/workflows/ci-workflow-macos_14_7.yml
@@ -4,31 +4,23 @@ on:
 #  pull_request:
 #    branches:
 #      - integration
-
   workflow_dispatch:
-
-#  push:
-#    branches:
-#      - update-4.1.4-freebsd-update
+    inputs:
+      tests_to_run:
+        description: 'Space-separated list of tests to run (e.g., "test1 test2"). Leave blank to run all.'
+        required: false
+        default: ''
 
 jobs:
   build-and-test:
-    runs-on: [self-hosted, macOS, X64, 14.7] 
-
+    runs-on: [self-hosted, macOS, X64, 14.7]
     steps:
       - name: Clean up workspace
         run: |
           rm -rf $GITHUB_WORKSPACE/*
-          
+
       - name: Checkout repository
-        uses: actions/checkout@v4  # Checkout the code from the repository
-
-      #- name: Set up dependencies
-      #run: |
-        #brew update
-        #brew install autoconf automake libtool bash python3 gcc make
-
-      # assume dependencies are all already setup
+        uses: actions/checkout@v4
 
       - name: Display OS and Arch
         run: |
@@ -56,30 +48,36 @@ jobs:
             make buildcheck
             sudo ./fix-macos-mbedtls-lib-links.sh /usr/local/lib /usr/local/bin ./
             cd tests
-            ./runtests
+            if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.tests_to_run }}" ]; then
+              echo "Running specific tests: ${{ github.event.inputs.tests_to_run }}"
+              ./runtests ${{ github.event.inputs.tests_to_run }}
+            else
+              echo "Running all tests"
+              ./runtests
+            fi
           } > build-and-test.log 2>&1
 
       - name: Display Progress
-        if: ${{ always() }}  # Display progress even if tests were interrupted
-        run: | 
-          cat ./tests/progress | grep "FAILED" || { printf "No failed tests. \n"; exit 0; }
+        if: ${{ always() }}
+        run: |
+          cat ./tests/progress | grep "FAILED" || { printf "No failed tests.\n"; exit 0; }
 
       - name: Upload full build and test log
-        if: ${{ always() }}  # Capture log even if the previous step fails
+        if: ${{ always() }}
         uses: actions/upload-artifact@v4
         with:
           name: build-and-test-log-${{ env.TIMESTAMP }}
-          path: build-and-test.log  # Upload the entire stdout and stderr as an artifact
+          path: build-and-test.log
 
       - name: Upload progress file as artifact
-        if: ${{ always() }}  # Capture progress even if the previous step fails
+        if: ${{ always() }}
         uses: actions/upload-artifact@v4
         with:
           name: test-progress-${{ env.TIMESTAMP }}
-          path: ./tests/progress  # Upload the 'progress' file for later review
+          path: ./tests/progress
 
       - name: Clean up ION build
-        if: ${{ always() }}  # Clean up even if previous steps fails
+        if: ${{ always() }}
         run: |
           killm
           sudo make uninstall
diff --git a/.github/workflows/ci-workflow-ubuntu.yml b/.github/workflows/ci-workflow-ubuntu.yml
--- a/.github/workflows/ci-workflow-ubuntu.yml
+++ b/.github/workflows/ci-workflow-ubuntu.yml
@@ -4,22 +4,20 @@ on:
   pull_request:
     branches:
       - integration
-
   workflow_dispatch:
-
-#  push:
-#    branches:
-#      - update-4.1.4-freebsd-update
+    inputs:
+      tests_to_run:
+        description: 'Space-separated list of tests to run (e.g., "test1 test2"). Leave blank to run all.'
+        required: false
+        default: ''
 
 jobs:
   build-and-test:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v4  # Checkout the code from the repository
+        uses: actions/checkout@v4
 
-      # Github Cloud Server container runs with passwordless `sudo`
       - name: Display OS and Arch
         run: |
           cat /etc/os-release
@@ -28,22 +26,22 @@ jobs:
           echo "User ID:"
           id
           echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
-      
+
       - name: Set up dependencies
         run: |
           sudo apt-get update
-          sudo apt-get install -y autoconf automake libtool bash python3 gcc make wget iptables # Install dependencies
+          sudo apt-get install -y autoconf automake libtool bash python3 gcc make wget iptables
 
       - name: Install MBEDTLS 2.28.9
         run: |
-            wget https://github.com/Mbed-TLS/mbedtls/releases/download/mbedtls-2.28.9/mbedtls-2.28.9.tar.bz2
-            sha256sum "mbedtls-2.28.9.tar.bz2" | grep -q "^e85ea97aaf78dd6c0a5ba2e54dd5932ffa15f39abfc189c26beef7684630c02b " || exit 1
-            tar -jvxf mbedtls-2.28.9.tar.bz2
-            cd mbedtls-2.28.9/
-            sed -i '/#define MBEDTLS_NIST_KW_C/s/\/\///' "./include/mbedtls/config.h"
-            make SHARED=1
-            make check
-            sudo make install
+          wget https://github.com/Mbed-TLS/mbedtls/releases/download/mbedtls-2.28.9/mbedtls-2.28.9.tar.bz2
+          sha256sum "mbedtls-2.28.9.tar.bz2" | grep -q "^e85ea97aaf78dd6c0a5ba2e54dd5932ffa15f39abfc189c26beef7684630c02b " || exit 1
+          tar -jvxf mbedtls-2.28.9.tar.bz2
+          cd mbedtls-2.28.9/
+          sed -i '/#define MBEDTLS_NIST_KW_C/s/\/\///' "./include/mbedtls/config.h"
+          make SHARED=1
+          make check
+          sudo make install
 
       - name: Generate timestamp for file names
         id: timestamp
@@ -62,24 +60,30 @@ jobs:
             make buildcheck
             sudo ldconfig
             cd tests
-            ./runtests
+            if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.tests_to_run }}" ]; then
+              echo "Running specific tests: ${{ github.event.inputs.tests_to_run }}"
+              ./runtests ${{ github.event.inputs.tests_to_run }}
+            else
+              echo "Running all tests"
+              ./runtests
+            fi
           } > build-and-test.log 2>&1
 
       - name: Display Progress
-        if: ${{ always() }}  # Display progress even if tests were interrupted
-        run: | 
-          cat ./tests/progress | grep "FAILED" || { printf "No failed tests. \n"; exit 0; }
+        if: ${{ always() }}
+        run: |
+          cat ./tests/progress | grep "FAILED" || { printf "No failed tests.\n"; exit 0; }
 
       - name: Upload full build and test log
-        if: ${{ always() }}  # Capture log even if the previous step fails
+        if: ${{ always() }}
         uses: actions/upload-artifact@v4
         with:
           name: build-and-test-log-${{ env.TIMESTAMP }}
-          path: build-and-test.log  # Upload the entire stdout and stderr as an artifact
+          path: build-and-test.log
 
       - name: Upload progress file as artifact
-        if: ${{ always() }}  # Capture progress even if the previous step fails
+        if: ${{ always() }}
         uses: actions/upload-artifact@v4
         with:
           name: test-progress-${{ env.TIMESTAMP }}
-          path: ./tests/progress  # Upload the 'progress' file for later review
+          path: ./tests/progress
